### PR TITLE
feat(styles): enabled media mixins with string params

### PR DESCRIPTION
**Pull request by gfellerph**
This allows to call the media mixins with keys from the breakpoint list directly, e.g. `@include media.max(lg) { }`.

### CODE REVIEW

**Comment by oliverschuerch** [comment]
Easy fix:
image

**Review by oliverschuerch — APPROVED** [review]
Isn't this a feature we should have a changeset for?
At least for the users using our scss files.

**Review by oliverschuerch — CHANGES_REQUESTED** [review]
Fix the lint issues and add a changset (if necessary)

**Comment by gfellerph** [comment]
> Isn't this a feature we should have a changeset for? At least for the users using our scss files.

This was not documented and not available in v9.

**Review by oliverschuerch — APPROVED** [review]

**Pull request merged**
