### PR TITLE
feat(styles): add list inline styles and update docs

### PR DESCRIPTION
**Pull request by gfellerph**

### CODE REVIEW

**Comment by oliverschuerch** [comment]
This will be added with #4097

**Comment by oliverschuerch** [comment]
@gfellerph please check if this PR is still needed, as a `list-inline` mixin and class have already been implemented.

**Review by oliverschuerch — CHANGES_REQUESTED** [review]
@gfellerph please check if this PR is still needed, as a list-inline mixin and class have already been implemented.

**Comment by gfellerph** [comment]
Closing as duplicate

**Pull request closed without merging**
