### PR TITLE
fix(components): fix post-collapsible invalid selector error

### PR DESCRIPTION
**Pull request by alizedebray**

### CODE REVIEW

**Review by gfellerph — APPROVED** [review]
@alizedebray can you cherry pick on v8 as well?

**Review by oliverschuerch — CHANGES_REQUESTED** [review]
The follow up error still exists

**Comment by alizedebray** [comment]
> @alizedebray can you cherry pick on v8 as well?
It is this PR: #3727

**Comment by oliverschuerch** [comment]
> @alizedebray can you cherry pick on v8 as well?

Same for v7

**Review by oliverschuerch — APPROVED** [review]

**Pull request merged**
