### PR TITLE
chore: update contribution guidelines

### PR DESCRIPTION
**Pull request by gfellerph**

### CODE REVIEW

**Review by imagoiq — CHANGES_REQUESTED** [review]
The images are too heavy (especially the radar). I don't think it's necessary to have it in 5k (+ there is the figma title)

Here are some optimized versions: 
88a8d899-6d3f-4f08-bf32-2f1328252d67 _1000

cb114c7a-d14a-4cb8-842f-eaa8f503607c

**Comment by gfellerph** [comment]
Updated the file links, thx @imagoiq.

**Review by imagoiq — APPROVED** [review]
Good!

By the way, should we add Typescript to the radar as well?

**Comment by gfellerph** [comment]
> Good!
> 
> By the way, should we add Typescript to the radar as well?

It's almost a given at this point, but why not.

**Pull request merged**
