### PR TITLE
feat(internet-header): expose CSS custom properties

### PR DESCRIPTION
**Pull request by alizedebray**

### CODE REVIEW

**Review by gfellerph — COMMENTED** [review]
@alizedebray I think this is the way to go. Are the global styles delivered via JS or do the projects have to import an additional CSS file?

**Comment by alizedebray** [comment]
> @alizedebray I think this is the way to go. Are the global styles delivered via JS or do the projects have to import an additional CSS file?

@gfellerph global styles have to be added manually by the consumers. This is why I declared the variables both on the `:root` and on the `:host`, this way you only have to import the global styles if you need to use the custom variables. What do you think?

**Comment by gfellerph** [comment]
> @gfellerph global styles have to be added manually by the consumers. This is why I declared the variables both on the `:root` and on the `:host`, this way you only have to import the global styles if you need to use the custom variables. What do you think?

That's perfect. Can you please add documentation how to do that?

> The main drawback with this approach (apart from duplication) is that is makes the header height customizable... Otherwise we could expose the SCSS variables but then it is no longer framework agnostic.

I think that's negligible. If you want to break the header, there are a thousand ways to do so. Setting this variable by mistake is an easy fix.

**Comment by alizedebray** [comment]
> Can you please add documentation how to do that?

Sure I added the documentation this morning: https://preview-3200--swisspost-design-system-next.netlify.app/?path=/docs/bfdf4e7c-37d3-40f8-a5d0-734f3e6612b5--docs

**Review by gfellerph — APPROVED** [review]
Good work!

**Pull request merged**
