### PR TITLE
feat(textarea): update resizer to match figma for webkit

### PR DESCRIPTION
**Pull request by RedlineTriad**
fire and forget

### CODE REVIEW

**Comment by swisspost-devs** [comment]
Preview environments are getting posted here, as soon as they are ready!

**Review by oliverschuerch — COMMENTED** [review]
This will not work in Firefox!

> "This feature is non-standard and should not be used without careful consideration."

Source: [caniuse.com](https://caniuse.com/mdn-css_selectors_-webkit-resizer)

**Comment by RedlineTriad** [comment]
Thats why I mentioned it in the title that it will only work for webkit, but @gfellerph said that it would still be an improvement.

**Comment by gfellerph** [comment]
> Thats why I mentioned it in the title that it will only work for webkit, but @gfellerph said that it would still be an improvement.

I'd call it progressive enhancement. It's non-critical for the correct functioning of the text-area, just looks nice for the browsers that support it.

**Comment by oliverschuerch** [comment]
Duplicate of #1765.

**Pull request closed without merging**
