### PR TITLE
feat!: rename everything

### PR DESCRIPTION
**Pull request by gfellerph**

### CODE REVIEW

**Comment by oliverschuerch** [comment]
@gfellerph can you try `pnpm start:styles` in the main package.json?
I get some errors from storybook, when I try this.

**Comment by oliverschuerch** [comment]
Import Error in the File:
[packages/components-angular/projects/intranet-header-showcase/src/app/app.module.ts](https://github.com/swisspost/design-system/blob/55a949ce1c5dea54e40942bca82ce7c815f8558f/packages/components-angular/projects/intranet-header-showcase/src/app/app.module.ts) line 4
```javascript
import { SwissPostIntranetHeaderModule } from 'swisspost-intranet-header';
```

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-styles reset` one after the other, an error occurs:

```javascript
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-styles@5.0.0-alpha.6 reset: `rimraf node_modules package-lock.json && npm run clean`
Exit status 1
```

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-styles lint` one after the other, an error occurs:

```javascript
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-styles@5.0.0-alpha.6 lint: `stylelint src/**/*.scss`
Exit status 2
```

ℹ️ The script `pnpm --filter design-system-styles lint:fix` works fine.

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-styles storybook` one after the other, many error occurs with the same info:

```
ERROR in ./src/post-basics.scss
Module build failed (from C:/GIT/swisspost/design-system/node_modules/.pnpm/style-loader@3.3.1/node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\GIT\swisspost\design-system\node_modules\.pnpm\style-loader@3.3.1\node_modules\style-loader\dist\index.js:19:24)
 @ ./.storybook/preview.js 1:0-33
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+core-client@6.5.9_5f7f4oajfffdifcutnf2ilgsam/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+core-client@6.5.9_5f7f4oajfffdifcutnf2ilgsam/node_modules/@storybook/core-client/dist/esm/globals/globals.js C:/GIT/swisspost/design-system/node_modules/.pnpm/webpack-hot-middleware@2.25.1/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./storybook-init-framework-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+html@6.5.9_@babel+core@7.18.10/node_modules/@storybook/html/dist/esm/client/preview/config-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+html@6.5.9_@babel+core@7.18.10/node_modules/@storybook/html/dist/esm/client/docs/config-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-links@6.5.9/node_modules/@storybook/addon-links/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-docs@6.5.9_@babel+core@7.18.10/node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-actions@6.5.9/node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-backgrounds@6.5.9/node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-measure@6.5.9/node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-outline@6.5.9/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js C:/GIT/swisspost/design-system/node_modules/.pnpm/@storybook+addon-interactions@6.5.9/node_modules/@storybook/addon-interactions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
```

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-styles build:storybook` one after the other, an error occurs:

```javascript
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-styles@5.0.0-alpha.6 build:storybook: `build-storybook`
Exit status 1
```

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo reset` one after the other, an error occurs:

```javascript
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-demo@5.0.0-alpha.4 reset: `rimraf node_modules package-lock.json && npm run clean`
Exit status 1
```

**Comment by gfellerph** [comment]
> When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo reset` one after the other, an error occurs:
> 
> ```js
> ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-demo@5.0.0-alpha.4 reset: `rimraf node_modules package-lock.json && npm run clean`
> Exit status 1
> ```

Removed the script as it's broken anyways and not needed anymore.

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo test` one after the other, every single karma-test fails.
It is unclear whether this was already the case before the renamings?

**Comment by gfellerph** [comment]
> When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo test` one after the other, every single karma-test fails. It is unclear whether this was already the case before the renamings?
> 
> 

Karma tests for all the packages are not set up

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo e2e` one after the other, some errors occurs:

```js
Jasmine started

  workspace-project App
    × should display welcome message
      - Expected 'Swiss Post' to equal 'Welcome to app!'.

**************************************************
*                    Failures                    *
**************************************************

1) workspace-project App should display welcome message
  - Expected 'Swiss Post' to equal 'Welcome to app!'.

Executed 1 of 1 spec (1 FAILED) in 2 secs.
```

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo e2e` one after the other, an error occurs:

```js
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-demo@5.0.0-alpha.4 ng: `ng "e2e"`
Exit status 1
```

**Comment by gfellerph** [comment]
> When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-demo e2e` one after the other, an error occurs:
> 
> ```js
> ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-demo@5.0.0-alpha.4 ng: `ng "e2e"`
> Exit status 1
> ```

e2e tests are not set up either

**Comment by oliverschuerch** [comment]
When running the scripts `pnpm bootstrap` and `pnpm --filter design-system-components-angular clean` one after the other, an error occurs:

```js
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @swisspost/design-system-components-angular@0.0.1-alpha.0 clean: `rimraf dist`
Exit status 1
```

**Review by oliverschuerch — APPROVED** [review]

**Pull request merged**
