### PR TITLE
fix: add italic defintion to fonts.scss

### PR DESCRIPTION
**Pull request by yannikstuker**

### CODE REVIEW

**Comment by swisspost-devs** [comment]
Preview environments are getting posted here, as soon as they are ready!

**Review by oliverschuerch — COMMENTED** [review]
Why did you removed the `options.$font-base-path` variable?

We should consider adding the `font-base-path` again to all `@font-face` definitions or remove the option variable itself (would be a breaking change).

**Comment by yannikstuker** [comment]
It was not intentional to delete the variable, I readded them

**Review by gfellerph — APPROVED** [review]

**Comment by gfellerph** [comment]
@yannikstuker thank you for contributing!

**Pull request merged**
